package visao;


import controle.ControlePatrimonio;
import controle.ControleSalas;
import modelo.Patrimonio;
import modelo.Sala;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Responsavel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class TelaManutPatrimonio extends javax.swing.JFrame {

    // Lista (model) do JList - utilizada para a inserção e 
    // eliminação dos elementos que aparecerão na interface
    // Criando a lista
    DefaultListModel<Patrimonio> listaPatrimonio = new DefaultListModel<>();
    
    // criando um arraylist para conter a lista de salas 
    ArrayList<Sala> listaSalas = new ArrayList<>();
    ControleSalas contsala = new ControleSalas();
    ControlePatrimonio contPatrimonio = new ControlePatrimonio();
    Responsavel respSelecionado;
    
    public TelaManutPatrimonio() {
        initComponents();
    
        // colocar elementos no arraylist de salas
        // popular a caixa de combinação com os elementos do arraylist
        // antes de adicionar os elementos na caixa de combinação fazer:
        // - trocar o tipo do combo de string para o tipo desejado
        //   utilizando a aba code da janela properties
        // - apagar os elementos da propriedade model
        listaSalas.addAll(contsala.listarTodas());   
        
        for(Sala s : listaSalas)
        {
            comboSala.addItem(s);
        }
        
        // associando a lista em memória à lista da tela 
        for(Patrimonio p :contPatrimonio.listarTodas()){
           listaPatrimonio.addElement(p);
        }   
        ListBoxPatrimonio.setModel(listaPatrimonio);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumPatrimonio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        botInserir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListBoxPatrimonio = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        botRemover = new javax.swing.JButton();
        botSair = new javax.swing.JButton();
        botLimpar = new javax.swing.JButton();
        botAlterar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        botPesquisar = new javax.swing.JButton();
        dataAquisicao = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        dataDesfazimento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        comboSala = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNomeResponsavel = new javax.swing.JTextField();
        btnResponsavel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Número");

        jLabel2.setText("Valor");

        jLabel3.setText("Descrição");

        botInserir.setText("Inserir");
        botInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInserirActionPerformed(evt);
            }
        });

        ListBoxPatrimonio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListBoxPatrimonioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListBoxPatrimonio);

        jLabel4.setText("Bens Patrimoniados");

        botRemover.setText("Remover");
        botRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRemoverActionPerformed(evt);
            }
        });

        botSair.setText("Sair");
        botSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSairActionPerformed(evt);
            }
        });

        botLimpar.setText("Limpar");
        botLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimparActionPerformed(evt);
            }
        });

        botAlterar.setText("Alterar");
        botAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAlterarActionPerformed(evt);
            }
        });

        jLabel5.setText("Pesquisar");

        botPesquisar.setText(">");
        botPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisarActionPerformed(evt);
            }
        });

        jLabel6.setText("Data Aquisição");

        jLabel7.setText("Data Desfazimento");

        comboSala.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSalaItemStateChanged(evt);
            }
        });
        comboSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSalaActionPerformed(evt);
            }
        });

        jLabel8.setText("Sala");

        jLabel9.setText("Responsavel");

        btnResponsavel.setText("?");
        btnResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponsavelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(272, 272, 272)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botSair, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(botAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(botPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(72, 72, 72))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNumPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dataAquisicao, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                                .addComponent(txtValor))
                                            .addGap(30, 30, 30)
                                            .addComponent(dataDesfazimento, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtDescricao)
                                        .addComponent(comboSala, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnResponsavel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botPesquisar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(dataAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataDesfazimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResponsavel))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botInserir)
                            .addComponent(botAlterar)
                            .addComponent(botLimpar))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botRemover)
                            .addComponent(botSair))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInserirActionPerformed
        
        // criando um objeto da classe Patrimonio
        Patrimonio p = new Patrimonio();
        
        // preenchendo os atributos do objeto 
        p.setNumero(Integer.parseInt(txtNumPatrimonio.getText()));
        p.setValor(Double.parseDouble(txtValor.getText()));
        p.setDescricao(txtDescricao.getText());
        p.setDataaquisicao(dataAquisicao.getDate());
        p.setDataDesfazimento(dataDesfazimento.getDate());
        
        // coloca o item selecionado da caixa de combinação
        // na sala do objeto
        p.setSala((Sala) comboSala.getSelectedItem());
        p.setResponsavel(this.respSelecionado);
               
        // adicionando o objeto à lista (model)
        listaPatrimonio.addElement(p);
        contPatrimonio.inserir(p);
        limparCampos();
    }//GEN-LAST:event_botInserirActionPerformed

    private void limparCampos()
    {
        // limpando os campos
        txtValor.setText("");
        txtNumPatrimonio.setText("");
        txtDescricao.setText("");    
        dataAquisicao.setDate(null);
        dataDesfazimento.setDate(null);  
        txtNomeResponsavel.setText("");
    }
    
    private void botRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRemoverActionPerformed
        
        // pegar a linha selecionada pelo usuário
        int linha = ListBoxPatrimonio.getSelectedIndex();
        
        // verificar se foi selecionada uma linha
        // -1 indica que não há linhas selecionadas
        if (linha == -1)
        {
            // apresenta uma mensagem ao usuário, indicando que
            // ele não selecionou nenhum patrimonio para exclusão
            JOptionPane.showMessageDialog(this, 
                        "Nenhum bem patrimoniado foi selecionado");
        }
        else
        {
            // ocorre quando o usuário seleciona uma linha no listbox
            
            // remove o elemento que foi selecionado   
            contPatrimonio.excluir(listaPatrimonio.get(linha));
            listaPatrimonio.remove(linha);

            limparCampos();
        }
        
        
    }//GEN-LAST:event_botRemoverActionPerformed

    private void ListBoxPatrimonioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListBoxPatrimonioMouseClicked
               
        // pega a posicao selecionada no listbox
        int posicao = ListBoxPatrimonio.getSelectedIndex();
        
        // pega o patrimonio  na lista de patrimonios
        Patrimonio p = listaPatrimonio.elementAt(posicao);
        this.respSelecionado=p.getResponsavel();
        
        // colocar os atributos na tela
        txtNumPatrimonio.setText(String.valueOf(p.getNumero()));
        txtValor.setText(String.valueOf(p.getValor()));
        txtDescricao.setText(p.getDescricao());
        dataAquisicao.setDate(p.getDataaquisicao());
        dataDesfazimento.setDate(p.getDataDesfazimento());
        txtNomeResponsavel.setText(p.getResponsavel().getNome());
        
        // define o combo como sendo a sala do objeto selecionado
        comboSala.setSelectedItem(p.getSala());
        
    }//GEN-LAST:event_ListBoxPatrimonioMouseClicked

    private void botLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_botLimparActionPerformed

    private void botAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAlterarActionPerformed

        // pega o número do item selecionado na listbox
        int nrItem = ListBoxPatrimonio.getSelectedIndex();
        
        // verificar se foi selecionado um item
        if (nrItem == -1)
        {
            // não foi selecionado nenhum item da lista
            // apresentar uma mensagem
            JOptionPane.showMessageDialog(this, "Um bem patrimoniado deve ser selecionada");           
        }
        else
        {
            // um item foi selecionado na lista
            
            // cria um novo objeto para sobrepor o antigo
            Patrimonio p = new Patrimonio();
            
            // preencher o objeto com os dados da interface
            p.setNumero(Integer.parseInt(txtNumPatrimonio.getText()));
            p.setValor(Double.parseDouble(txtValor.getText()));
            p.setDescricao(txtDescricao.getText());
            p.setDataaquisicao(dataAquisicao.getDate());
            p.setDataDesfazimento(dataDesfazimento.getDate());
            p.setSala((Sala) comboSala.getSelectedItem());
            p.setResponsavel(this.respSelecionado);
            
            // atualizar o elemento da posicao selecionada
            listaPatrimonio.setElementAt(p, nrItem);
            contPatrimonio.alterar(p);
            
            limparCampos();
        }
    }//GEN-LAST:event_botAlterarActionPerformed

    private void comboSalaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSalaItemStateChanged
        // TODO add your handling code here:
                // pegar o elemento selecionado
        Sala s = (Sala) comboSala.getSelectedItem();
        
        // colocar o valor no label
       // jLabel9.setText(s.getDescricao());
    }//GEN-LAST:event_comboSalaItemStateChanged

    private void btnResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponsavelActionPerformed
        PesqResponsavel tela = new PesqResponsavel(null,true);
        tela.setVisible(true);
        if(tela.isSelecionado()){
           this.respSelecionado = tela.getRespAtual();
           txtNomeResponsavel.setText(this.respSelecionado.getNome());
        }   
    }//GEN-LAST:event_btnResponsavelActionPerformed

    private void botSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSairActionPerformed
        dispose();
    }//GEN-LAST:event_botSairActionPerformed

    private void botPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisarActionPerformed
        listaPatrimonio.clear();
        List<Patrimonio> lista = new ArrayList<>();
        lista.addAll(contPatrimonio.listarPorNome("%"+txtPesquisar.getText()+"%"));
        for(Patrimonio p :lista){
            listaPatrimonio.addElement(p);
        }            
    }//GEN-LAST:event_botPesquisarActionPerformed

    private void comboSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManutPatrimonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManutPatrimonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManutPatrimonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManutPatrimonio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaManutPatrimonio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Patrimonio> ListBoxPatrimonio;
    private javax.swing.JButton botAlterar;
    private javax.swing.JButton botInserir;
    private javax.swing.JButton botLimpar;
    private javax.swing.JButton botPesquisar;
    private javax.swing.JButton botRemover;
    private javax.swing.JButton botSair;
    private javax.swing.JButton btnResponsavel;
    private javax.swing.JComboBox<Sala> comboSala;
    private com.toedter.calendar.JDateChooser dataAquisicao;
    private com.toedter.calendar.JDateChooser dataDesfazimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNomeResponsavel;
    private javax.swing.JTextField txtNumPatrimonio;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
