/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleSala;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.salas;

/**
 *
 * @author Aluno
 */
public class TelaManutencaoSala extends javax.swing.JDialog {

     private ControleSala controlesala = new ControleSala();
    private ArrayList<salas> listaSalas = new ArrayList();
    
    /**
     * Creates new form TelaManutencaoSala
     */
    public TelaManutencaoSala(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    atualizaTabela(true);
    }

    public void atualizaTabela(boolean flag){
    DefaultTableModel modelo = (DefaultTableModel) TabelaSalas.getModel();
    if(flag){
    listaSalas.clear();
    listaSalas.addAll(controlesala.listarTodos());
    }
    
    while (modelo.getRowCount()>0){
    
        modelo.removeRow(0);
    
    }
    
    for(salas s: listaSalas){
    modelo.addRow(new Object[] {s.getNumero(), s.getDescricao(), s.getBloco() });
    }
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listar = new javax.swing.JButton();
        incluir = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        fechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaSalas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNumsala = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBloco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        listar.setBackground(new java.awt.Color(255, 153, 255));
        listar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listar.setForeground(new java.awt.Color(0, 0, 255));
        listar.setText("LISTAR");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });
        jPanel1.add(listar);

        incluir.setBackground(new java.awt.Color(255, 153, 255));
        incluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        incluir.setForeground(new java.awt.Color(0, 0, 255));
        incluir.setText("INCLUIR");
        incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirActionPerformed(evt);
            }
        });
        jPanel1.add(incluir);

        excluir.setBackground(new java.awt.Color(255, 153, 255));
        excluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        excluir.setForeground(new java.awt.Color(0, 0, 255));
        excluir.setText("EXCLUIR");
        jPanel1.add(excluir);

        alterar.setBackground(new java.awt.Color(255, 153, 255));
        alterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alterar.setForeground(new java.awt.Color(0, 0, 255));
        alterar.setText("ALTERAR");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        jPanel1.add(alterar);

        fechar.setBackground(new java.awt.Color(204, 51, 0));
        fechar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fechar.setText("FECHAR");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });
        jPanel1.add(fechar);

        TabelaSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NUMERO", "DESCRICAO", "BLOCO"
            }
        ));
        TabelaSalas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TabelaSalasMouseMoved(evt);
            }
        });
        TabelaSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaSalasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaSalas);

        jLabel1.setText("NUMERO:");

        jLabel2.setText("BLOCO:");

        jLabel3.setText("DERCRIÇAO");

        pesquisar.setBackground(new java.awt.Color(255, 153, 255));
        pesquisar.setForeground(new java.awt.Color(0, 0, 255));
        pesquisar.setText("PESQUISAR");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText("SALAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumsala, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel4)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisar)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumsala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_fecharActionPerformed

    private void TabelaSalasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaSalasMouseMoved
        // TODO add your handling code here:
        
    
        
        
    }//GEN-LAST:event_TabelaSalasMouseMoved

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        // TODO add your handling code here:
        int nrItem = TabelaSalas.getSelectedRow();
        if(nrItem == -1){
        JOptionPane.showInputDialog(this, "selecione Uma sala");
        
        }
                
        else{
        salas s = new salas();
        s.setNumero(Integer.parseInt(txtNumsala.getText()));
        s.setBloco(Integer.parseInt(txtBloco.getText()));
        s.setDescricao(txtDescricao.getText());
        
        controlesala.alterar(s);
        atualizaTabela(true);
        }
        
        
    }//GEN-LAST:event_alterarActionPerformed

    private void TabelaSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaSalasMouseClicked
        // TODO add your handling code here:
        int posicao = TabelaSalas.getSelectedRow();
           salas s = listaSalas.get(posicao); 
       txtNumsala.setText(String.valueOf(s.getNumero()));
      txtBloco.setText(String.valueOf(s.getBloco()));
        txtDescricao.setText(String.valueOf(s.getDescricao()));
        
    }//GEN-LAST:event_TabelaSalasMouseClicked

    private void incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirActionPerformed
        // TODO add your handling code here:
         salas s = new salas();
        s.setNumero(Integer.valueOf(txtNumsala.getText()));
        s.setBloco(Integer.valueOf(txtBloco.getText()));
        s.setDescricao(txtDescricao.getText());
        controlesala.inserir(s);
        atualizaTabela(true);
    }//GEN-LAST:event_incluirActionPerformed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManutencaoSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaManutencaoSala dialog = new TelaManutencaoSala(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaSalas;
    private javax.swing.JButton alterar;
    private javax.swing.JButton excluir;
    private javax.swing.JButton fechar;
    private javax.swing.JButton incluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listar;
    private javax.swing.JButton pesquisar;
    private javax.swing.JTextField txtBloco;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNumsala;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
