/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bingo;

import java.util.Random;
import javafx.scene.paint.Color;
import javax.swing.JButton;


/**
 *
 * @author Aluno
 */
public class JogoBingo extends javax.swing.JFrame {

    /**
     * Creates new form JogoBingo
     */
    
    
   
    JButton[] botoes = new JButton[75];
    int[] numero = new int[75];
    int[] sorteados = new int[75];
    int n1, n2, n3;
    int cont=0;
    
    Random sorte = new Random();
    
    public JogoBingo() {
        initComponents();
        
        botoes[0]=bt1;
        botoes[1]=bt2;
        botoes[2]=bt3;
        botoes[3]=bt4;
        botoes[4]=bt5;   
        botoes[5]=bt6;
        botoes[6]=bt7;
        botoes[7]=bt8;
        botoes[8]=bt9;
        botoes[9]=bt10;
        botoes[10]=bt11;
        botoes[11]=bt12;
        botoes[12]=bt13;
        botoes[13]=bt14;
        botoes[14]=bt15;
        botoes[15]=bt16;
        botoes[16]=bt17;
        botoes[17]=bt18;
        botoes[18]=bt19;
        botoes[19]=bt20;
        botoes[20]=bt21;
        botoes[21]=bt22;
        botoes[22]=bt23;
        botoes[23]=bt24;
        botoes[24]=bt25;
        botoes[25]=bt26;
        botoes[26]=bt27;
        botoes[27]=bt28;
        botoes[28]=bt29;
        botoes[29]=bt30;
        botoes[30]=bt31;
        botoes[31]=bt32;
        botoes[32]=bt33;
        botoes[33]=bt34;
        botoes[34]=bt35;
        botoes[35]=bt36;
        botoes[36]=bt37;
        botoes[37]=bt38;
        botoes[38]=bt39;
        botoes[39]=bt40;
        botoes[40]=bt41;
        botoes[41]=bt42;
        botoes[42]=bt43;
        botoes[43]=bt44;
        botoes[44]=bt45;
        botoes[45]=bt46;
        botoes[46]=bt47;
        botoes[47]=bt48;
        botoes[48]=bt49;
        botoes[49]=bt50;
        botoes[50]=bt51;
        botoes[51]=bt52;
        botoes[52]=bt53;
        botoes[53]=bt54;
        botoes[54]=bt55;
        botoes[55]=bt56;
        botoes[56]=bt57;
        botoes[57]=bt58;
        botoes[58]=bt59;
        botoes[59]=bt60;
        botoes[60]=bt61;
        botoes[61]=bt62;
        botoes[62]=bt63;
        botoes[63]=bt64;
        botoes[64]=bt65;
        botoes[65]=bt66;
        botoes[66]=bt67;
        botoes[67]=bt68;
        botoes[68]=bt69;
        botoes[69]=bt70;
        botoes[70]=bt71;
        botoes[71]=bt72;
        botoes[72]=bt73;
        botoes[73]=bt74;
        botoes[74]=bt75;
       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton42 = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        posi1 = new javax.swing.JTextField();
        posi2 = new javax.swing.JTextField();
        posi3 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt10 = new javax.swing.JButton();
        bt13 = new javax.swing.JButton();
        bt16 = new javax.swing.JButton();
        bt15 = new javax.swing.JButton();
        bt14 = new javax.swing.JButton();
        bt19 = new javax.swing.JButton();
        bt18 = new javax.swing.JButton();
        bt17 = new javax.swing.JButton();
        bt20 = new javax.swing.JButton();
        bt12 = new javax.swing.JButton();
        bt11 = new javax.swing.JButton();
        bt35 = new javax.swing.JButton();
        bt23 = new javax.swing.JButton();
        bt34 = new javax.swing.JButton();
        bt26 = new javax.swing.JButton();
        bt39 = new javax.swing.JButton();
        bt25 = new javax.swing.JButton();
        bt38 = new javax.swing.JButton();
        bt24 = new javax.swing.JButton();
        bt37 = new javax.swing.JButton();
        bt29 = new javax.swing.JButton();
        bt40 = new javax.swing.JButton();
        bt28 = new javax.swing.JButton();
        bt32 = new javax.swing.JButton();
        bt27 = new javax.swing.JButton();
        bt31 = new javax.swing.JButton();
        bt30 = new javax.swing.JButton();
        bt33 = new javax.swing.JButton();
        bt36 = new javax.swing.JButton();
        bt22 = new javax.swing.JButton();
        bt21 = new javax.swing.JButton();
        bt55 = new javax.swing.JButton();
        bt54 = new javax.swing.JButton();
        bt59 = new javax.swing.JButton();
        bt58 = new javax.swing.JButton();
        bt57 = new javax.swing.JButton();
        bt60 = new javax.swing.JButton();
        bt52 = new javax.swing.JButton();
        bt51 = new javax.swing.JButton();
        bt75 = new javax.swing.JButton();
        bt63 = new javax.swing.JButton();
        bt72 = new javax.swing.JButton();
        bt67 = new javax.swing.JButton();
        bt42 = new javax.swing.JButton();
        bt71 = new javax.swing.JButton();
        bt41 = new javax.swing.JButton();
        bt70 = new javax.swing.JButton();
        bt73 = new javax.swing.JButton();
        bt62 = new javax.swing.JButton();
        bt61 = new javax.swing.JButton();
        bt43 = new javax.swing.JButton();
        bt46 = new javax.swing.JButton();
        bt45 = new javax.swing.JButton();
        bt44 = new javax.swing.JButton();
        bt49 = new javax.swing.JButton();
        bt48 = new javax.swing.JButton();
        bt47 = new javax.swing.JButton();
        bt50 = new javax.swing.JButton();
        bt53 = new javax.swing.JButton();
        bt56 = new javax.swing.JButton();
        bt74 = new javax.swing.JButton();
        bt66 = new javax.swing.JButton();
        bt65 = new javax.swing.JButton();
        bt64 = new javax.swing.JButton();
        bt69 = new javax.swing.JButton();
        bt68 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jButton42.setBackground(new java.awt.Color(204, 255, 204));
        jButton42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton42.setText("Sortear");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton42)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        total.setForeground(new java.awt.Color(255, 0, 0));
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Total");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ultimos numeros");

        posi1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        posi1.setForeground(new java.awt.Color(255, 0, 0));

        posi2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        posi2.setForeground(new java.awt.Color(255, 0, 0));
        posi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posi2ActionPerformed(evt);
            }
        });

        posi3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        posi3.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(total, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(posi1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(posi2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(posi3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(posi1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(posi2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(posi3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bt1.setBackground(new java.awt.Color(255, 0, 0));
        bt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt1.setForeground(new java.awt.Color(204, 255, 204));
        bt1.setText("1");

        bt2.setBackground(new java.awt.Color(255, 0, 0));
        bt2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt2.setForeground(new java.awt.Color(204, 255, 204));
        bt2.setText("2");

        bt3.setBackground(new java.awt.Color(255, 0, 0));
        bt3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt3.setForeground(new java.awt.Color(204, 255, 204));
        bt3.setText("3");

        bt6.setBackground(new java.awt.Color(255, 0, 0));
        bt6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt6.setForeground(new java.awt.Color(204, 255, 204));
        bt6.setText("6");

        bt5.setBackground(new java.awt.Color(255, 0, 0));
        bt5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt5.setForeground(new java.awt.Color(204, 255, 204));
        bt5.setText("5");

        bt4.setBackground(new java.awt.Color(255, 0, 0));
        bt4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt4.setForeground(new java.awt.Color(204, 255, 204));
        bt4.setText("4");

        bt9.setBackground(new java.awt.Color(255, 0, 0));
        bt9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt9.setForeground(new java.awt.Color(204, 255, 204));
        bt9.setText("9");

        bt8.setBackground(new java.awt.Color(255, 0, 0));
        bt8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt8.setForeground(new java.awt.Color(204, 255, 204));
        bt8.setText("8");

        bt7.setBackground(new java.awt.Color(255, 0, 0));
        bt7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt7.setForeground(new java.awt.Color(204, 255, 204));
        bt7.setText("7");

        bt10.setBackground(new java.awt.Color(255, 0, 0));
        bt10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt10.setForeground(new java.awt.Color(204, 255, 204));
        bt10.setText("10");

        bt13.setBackground(new java.awt.Color(255, 0, 0));
        bt13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt13.setForeground(new java.awt.Color(204, 255, 204));
        bt13.setText("13");

        bt16.setBackground(new java.awt.Color(255, 0, 0));
        bt16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt16.setForeground(new java.awt.Color(204, 255, 204));
        bt16.setText("16");

        bt15.setBackground(new java.awt.Color(255, 0, 0));
        bt15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt15.setForeground(new java.awt.Color(204, 255, 204));
        bt15.setText("15");

        bt14.setBackground(new java.awt.Color(255, 0, 0));
        bt14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt14.setForeground(new java.awt.Color(204, 255, 204));
        bt14.setText("14");

        bt19.setBackground(new java.awt.Color(255, 0, 0));
        bt19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt19.setForeground(new java.awt.Color(204, 255, 204));
        bt19.setText("19");

        bt18.setBackground(new java.awt.Color(255, 0, 0));
        bt18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt18.setForeground(new java.awt.Color(204, 255, 204));
        bt18.setText("18");

        bt17.setBackground(new java.awt.Color(255, 0, 0));
        bt17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt17.setForeground(new java.awt.Color(204, 255, 204));
        bt17.setText("17");

        bt20.setBackground(new java.awt.Color(255, 0, 0));
        bt20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt20.setForeground(new java.awt.Color(204, 255, 204));
        bt20.setText("20");

        bt12.setBackground(new java.awt.Color(255, 0, 0));
        bt12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt12.setForeground(new java.awt.Color(204, 255, 204));
        bt12.setText("12");

        bt11.setBackground(new java.awt.Color(255, 0, 0));
        bt11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt11.setForeground(new java.awt.Color(204, 255, 204));
        bt11.setText("11");

        bt35.setBackground(new java.awt.Color(255, 0, 0));
        bt35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt35.setForeground(new java.awt.Color(204, 255, 204));
        bt35.setText("35");

        bt23.setBackground(new java.awt.Color(255, 0, 0));
        bt23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt23.setForeground(new java.awt.Color(204, 255, 204));
        bt23.setText("23");

        bt34.setBackground(new java.awt.Color(255, 0, 0));
        bt34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt34.setForeground(new java.awt.Color(204, 255, 204));
        bt34.setText("34");

        bt26.setBackground(new java.awt.Color(255, 0, 0));
        bt26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt26.setForeground(new java.awt.Color(204, 255, 204));
        bt26.setText("26");

        bt39.setBackground(new java.awt.Color(255, 0, 0));
        bt39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt39.setForeground(new java.awt.Color(204, 255, 204));
        bt39.setText("39");

        bt25.setBackground(new java.awt.Color(255, 0, 0));
        bt25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt25.setForeground(new java.awt.Color(204, 255, 204));
        bt25.setText("25");

        bt38.setBackground(new java.awt.Color(255, 0, 0));
        bt38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt38.setForeground(new java.awt.Color(204, 255, 204));
        bt38.setText("38");

        bt24.setBackground(new java.awt.Color(255, 0, 0));
        bt24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt24.setForeground(new java.awt.Color(204, 255, 204));
        bt24.setText("24");

        bt37.setBackground(new java.awt.Color(255, 0, 0));
        bt37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt37.setForeground(new java.awt.Color(204, 255, 204));
        bt37.setText("37");

        bt29.setBackground(new java.awt.Color(255, 0, 0));
        bt29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt29.setForeground(new java.awt.Color(204, 255, 204));
        bt29.setText("29");

        bt40.setBackground(new java.awt.Color(255, 0, 0));
        bt40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt40.setForeground(new java.awt.Color(204, 255, 204));
        bt40.setText("40");

        bt28.setBackground(new java.awt.Color(255, 0, 0));
        bt28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt28.setForeground(new java.awt.Color(204, 255, 204));
        bt28.setText("28");

        bt32.setBackground(new java.awt.Color(255, 0, 0));
        bt32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt32.setForeground(new java.awt.Color(204, 255, 204));
        bt32.setText("32");

        bt27.setBackground(new java.awt.Color(255, 0, 0));
        bt27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt27.setForeground(new java.awt.Color(204, 255, 204));
        bt27.setText("27");

        bt31.setBackground(new java.awt.Color(255, 0, 0));
        bt31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt31.setForeground(new java.awt.Color(204, 255, 204));
        bt31.setText("31");

        bt30.setBackground(new java.awt.Color(255, 0, 0));
        bt30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt30.setForeground(new java.awt.Color(204, 255, 204));
        bt30.setText("30");

        bt33.setBackground(new java.awt.Color(255, 0, 0));
        bt33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt33.setForeground(new java.awt.Color(204, 255, 204));
        bt33.setText("33");

        bt36.setBackground(new java.awt.Color(255, 0, 0));
        bt36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt36.setForeground(new java.awt.Color(204, 255, 204));
        bt36.setText("36");

        bt22.setBackground(new java.awt.Color(255, 0, 0));
        bt22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt22.setForeground(new java.awt.Color(204, 255, 204));
        bt22.setText("22");

        bt21.setBackground(new java.awt.Color(255, 0, 0));
        bt21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt21.setForeground(new java.awt.Color(204, 255, 204));
        bt21.setText("21");

        bt55.setBackground(new java.awt.Color(255, 0, 0));
        bt55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt55.setForeground(new java.awt.Color(204, 255, 204));
        bt55.setText("55");

        bt54.setBackground(new java.awt.Color(255, 0, 0));
        bt54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt54.setForeground(new java.awt.Color(204, 255, 204));
        bt54.setText("54");

        bt59.setBackground(new java.awt.Color(255, 0, 0));
        bt59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt59.setForeground(new java.awt.Color(204, 255, 204));
        bt59.setText("59");

        bt58.setBackground(new java.awt.Color(255, 0, 0));
        bt58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt58.setForeground(new java.awt.Color(204, 255, 204));
        bt58.setText("58");

        bt57.setBackground(new java.awt.Color(255, 0, 0));
        bt57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt57.setForeground(new java.awt.Color(204, 255, 204));
        bt57.setText("57");

        bt60.setBackground(new java.awt.Color(255, 0, 0));
        bt60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt60.setForeground(new java.awt.Color(204, 255, 204));
        bt60.setText("60");

        bt52.setBackground(new java.awt.Color(255, 0, 0));
        bt52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt52.setForeground(new java.awt.Color(204, 255, 204));
        bt52.setText("52");

        bt51.setBackground(new java.awt.Color(255, 0, 0));
        bt51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt51.setForeground(new java.awt.Color(204, 255, 204));
        bt51.setText("51");

        bt75.setBackground(new java.awt.Color(255, 0, 0));
        bt75.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt75.setForeground(new java.awt.Color(204, 255, 204));
        bt75.setText("75");

        bt63.setBackground(new java.awt.Color(255, 0, 0));
        bt63.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt63.setForeground(new java.awt.Color(204, 255, 204));
        bt63.setText("63");

        bt72.setBackground(new java.awt.Color(255, 0, 0));
        bt72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt72.setForeground(new java.awt.Color(204, 255, 204));
        bt72.setText("72");

        bt67.setBackground(new java.awt.Color(255, 0, 0));
        bt67.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt67.setForeground(new java.awt.Color(204, 255, 204));
        bt67.setText("67");

        bt42.setBackground(new java.awt.Color(255, 0, 0));
        bt42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt42.setForeground(new java.awt.Color(204, 255, 204));
        bt42.setText("42");

        bt71.setBackground(new java.awt.Color(255, 0, 0));
        bt71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt71.setForeground(new java.awt.Color(204, 255, 204));
        bt71.setText("71");

        bt41.setBackground(new java.awt.Color(255, 0, 0));
        bt41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt41.setForeground(new java.awt.Color(204, 255, 204));
        bt41.setText("41");

        bt70.setBackground(new java.awt.Color(255, 0, 0));
        bt70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt70.setForeground(new java.awt.Color(204, 255, 204));
        bt70.setText("70");

        bt73.setBackground(new java.awt.Color(255, 0, 0));
        bt73.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt73.setForeground(new java.awt.Color(204, 255, 204));
        bt73.setText("73");

        bt62.setBackground(new java.awt.Color(255, 0, 0));
        bt62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt62.setForeground(new java.awt.Color(204, 255, 204));
        bt62.setText("62");

        bt61.setBackground(new java.awt.Color(255, 0, 0));
        bt61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt61.setForeground(new java.awt.Color(204, 255, 204));
        bt61.setText("61");

        bt43.setBackground(new java.awt.Color(255, 0, 0));
        bt43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt43.setForeground(new java.awt.Color(204, 255, 204));
        bt43.setText("43");

        bt46.setBackground(new java.awt.Color(255, 0, 0));
        bt46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt46.setForeground(new java.awt.Color(204, 255, 204));
        bt46.setText("46");

        bt45.setBackground(new java.awt.Color(255, 0, 0));
        bt45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt45.setForeground(new java.awt.Color(204, 255, 204));
        bt45.setText("45");

        bt44.setBackground(new java.awt.Color(255, 0, 0));
        bt44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt44.setForeground(new java.awt.Color(204, 255, 204));
        bt44.setText("44");

        bt49.setBackground(new java.awt.Color(255, 0, 0));
        bt49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt49.setForeground(new java.awt.Color(204, 255, 204));
        bt49.setText("49");

        bt48.setBackground(new java.awt.Color(255, 0, 0));
        bt48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt48.setForeground(new java.awt.Color(204, 255, 204));
        bt48.setText("48");

        bt47.setBackground(new java.awt.Color(255, 0, 0));
        bt47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt47.setForeground(new java.awt.Color(204, 255, 204));
        bt47.setText("47");

        bt50.setBackground(new java.awt.Color(255, 0, 0));
        bt50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt50.setForeground(new java.awt.Color(204, 255, 204));
        bt50.setText("50");

        bt53.setBackground(new java.awt.Color(255, 0, 0));
        bt53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt53.setForeground(new java.awt.Color(204, 255, 204));
        bt53.setText("53");

        bt56.setBackground(new java.awt.Color(255, 0, 0));
        bt56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt56.setForeground(new java.awt.Color(204, 255, 204));
        bt56.setText("56");

        bt74.setBackground(new java.awt.Color(255, 0, 0));
        bt74.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt74.setForeground(new java.awt.Color(204, 255, 204));
        bt74.setText("74");

        bt66.setBackground(new java.awt.Color(255, 0, 0));
        bt66.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt66.setForeground(new java.awt.Color(204, 255, 204));
        bt66.setText("66");

        bt65.setBackground(new java.awt.Color(255, 0, 0));
        bt65.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt65.setForeground(new java.awt.Color(204, 255, 204));
        bt65.setText("65");

        bt64.setBackground(new java.awt.Color(255, 0, 0));
        bt64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt64.setForeground(new java.awt.Color(204, 255, 204));
        bt64.setText("64");

        bt69.setBackground(new java.awt.Color(255, 0, 0));
        bt69.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt69.setForeground(new java.awt.Color(204, 255, 204));
        bt69.setText("69");

        bt68.setBackground(new java.awt.Color(255, 0, 0));
        bt68.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt68.setForeground(new java.awt.Color(204, 255, 204));
        bt68.setText("68");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt31, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt32, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt33, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt34, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt35, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt36, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt37, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt38, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt39, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt40, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt21, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt22, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt23, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt24, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt25, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt26, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt27, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt28, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt29, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt30, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt51, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt52, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt53, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt54, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt55, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt56, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt57, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt58, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt59, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt60, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt71, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt72, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt73, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt74, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt75, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt61, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt62, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt63, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt64, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt65, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt66, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt67, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt68, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt69, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt70, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt41, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt42, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt43, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt44, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt45, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt46, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt47, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt48, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt49, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt50, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt24, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt25, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt26, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt27, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt28, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt29, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt31, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt32, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt33, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt34, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt35, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt36, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt37, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt38, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt39, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt40, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt41, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt42, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt43, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt44, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt45, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt46, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt47, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt48, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt49, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt50, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt51, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt52, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt53, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt54, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt55, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt56, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt57, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt58, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt59, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt60, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt61, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt62, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt63, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt64, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt65, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt66, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt67, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt68, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt69, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt70, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt71, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt72, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt73, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt74, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt75, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        
         boolean flag = true;
           int val=0;
        
           while(flag){
        val = sorte.nextInt(75)+1;
    
       
        if(sorteados[val-1] == 0){
        flag=false;
        }
         sorteados[val-1]=1;
           }  
        
        System.out.println(val);
      botoes[val-1].setBackground(java.awt.Color.green);
      botoes[val-1].setForeground(java.awt.Color.red);
      
      if(sorteados[val-1] == 1){
      cont++;
      numero[cont]=val;
      total.setText(String.valueOf(cont));
      }
      
       n3=n2;
       n2=n1;
       n1=val;
      
     posi1.setText(String.valueOf(n1));
     posi2.setText(String.valueOf(n2));
     posi3.setText(String.valueOf(n3));
  

       

    
    }//GEN-LAST:event_jButton42ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
   
        
    }//GEN-LAST:event_totalActionPerformed

    private void posi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoBingo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt13;
    private javax.swing.JButton bt14;
    private javax.swing.JButton bt15;
    private javax.swing.JButton bt16;
    private javax.swing.JButton bt17;
    private javax.swing.JButton bt18;
    private javax.swing.JButton bt19;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt20;
    private javax.swing.JButton bt21;
    private javax.swing.JButton bt22;
    private javax.swing.JButton bt23;
    private javax.swing.JButton bt24;
    private javax.swing.JButton bt25;
    private javax.swing.JButton bt26;
    private javax.swing.JButton bt27;
    private javax.swing.JButton bt28;
    private javax.swing.JButton bt29;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt30;
    private javax.swing.JButton bt31;
    private javax.swing.JButton bt32;
    private javax.swing.JButton bt33;
    private javax.swing.JButton bt34;
    private javax.swing.JButton bt35;
    private javax.swing.JButton bt36;
    private javax.swing.JButton bt37;
    private javax.swing.JButton bt38;
    private javax.swing.JButton bt39;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt40;
    private javax.swing.JButton bt41;
    private javax.swing.JButton bt42;
    private javax.swing.JButton bt43;
    private javax.swing.JButton bt44;
    private javax.swing.JButton bt45;
    private javax.swing.JButton bt46;
    private javax.swing.JButton bt47;
    private javax.swing.JButton bt48;
    private javax.swing.JButton bt49;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt50;
    private javax.swing.JButton bt51;
    private javax.swing.JButton bt52;
    private javax.swing.JButton bt53;
    private javax.swing.JButton bt54;
    private javax.swing.JButton bt55;
    private javax.swing.JButton bt56;
    private javax.swing.JButton bt57;
    private javax.swing.JButton bt58;
    private javax.swing.JButton bt59;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt60;
    private javax.swing.JButton bt61;
    private javax.swing.JButton bt62;
    private javax.swing.JButton bt63;
    private javax.swing.JButton bt64;
    private javax.swing.JButton bt65;
    private javax.swing.JButton bt66;
    private javax.swing.JButton bt67;
    private javax.swing.JButton bt68;
    private javax.swing.JButton bt69;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt70;
    private javax.swing.JButton bt71;
    private javax.swing.JButton bt72;
    private javax.swing.JButton bt73;
    private javax.swing.JButton bt74;
    private javax.swing.JButton bt75;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton jButton42;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField posi1;
    private javax.swing.JTextField posi2;
    private javax.swing.JTextField posi3;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    
}

